### ISSUE TITLE
Not Appearing in Live Templates

### ISSUE THREAD

**Issue by putyourlightson** [BarrelStrength/PhpStorm-Live-Templates-Craft-CMS#3]
I've followed the following instructions:

1. Go to PhpStorm Preferences | Tools | Settings Repository
2. Add Read-only Source https://github.com/barrelstrength/PhpStorm-Live-Templates-Craft-CMS
3. Restart PhpStorm

But when I visit Preferences->Editor->Live Templates, I don't see `Craft CMS - Twig` or `Craft CMS - PHP Live Templates`. Any idea why that might be?

**Comment by BenParizek** [comment]
@putyourlightson Can you confirm what version of PhpStorm you are using? I believe support for this was added in version 2018.3

**Comment by putyourlightson** [comment]
Was on 2018.3, just updated to 2018.3.1 but still don't see it...

<img width="573" alt="screenshot 2018-12-09 at 20 13 08" src="https://user-images.githubusercontent.com/2318222/49701646-ddfe0300-fbee-11e8-84c4-abfd6fe8f9fb.png">

**Comment by BenParizek** [comment]
@putyourlightson Not sure what's up. Here's a short screencast of all the settings I'm using and how it seems to be working fine in my setup: http://share.barrelstrength.co/91574eebf098

See anything different worth noting?

**Comment by echantigny** [comment]
Ran into this exact same issue.  Disabled the Config Sync option and everything showed up.

**Comment by putyourlightson** [comment]
@echantigny Do you mean the "Auto Sync" option or something else?

<img width="501" alt="screenshot 2019-02-13 at 17 25 06" src="https://user-images.githubusercontent.com/2318222/52710052-5e0c6480-2fb4-11e9-8ade-80fdec0d2dfb.png">

**Comment by echantigny** [comment]
@putyourlightson. I mean the account cloud sync for settings.  I turned that off, added the links to your repos, they showed up.  I then turned the sync back on and they are still there.  Sounds like a phpstorm issue.

**Comment by echantigny** [comment]
@putyourlightson So, after rebooting my computer, I launched PHPStorm again and your Live Templates are gone again.  Turned off the "Sync to my JetBrains account" once again and poof, it's back.  This does sound like a PHPStorm bug so I would not really pay attention to this issue, other than pointing people in the right direction.

**Comment by putyourlightson** [comment]
@echantigny Can you show me a screenshot of the sync setting? Are you on 2018.3.x?

**Comment by echantigny** [comment]
This one, which changes when you are connected to your account.

Version 2018.3.4

![2019-02-14 08_46_11-great boardgames c__wamp64_www_great-boardgames - _templates_checkout_payme](https://user-images.githubusercontent.com/4933333/52790664-1c6fce00-3035-11e9-9cf5-68f42f608168.png)

**Comment by terryupton** [comment]
Also seeing this issue with both this plugin (live templates) and the twig ones.
not really wanting to disable my sync via my JetBrains account, any other solutions?

**Comment by dwhoban** [comment]
@terryupton alternative is to use a git repo for sync rather than Jetbrains account.

**Comment by terryupton** [comment]
@dwhoban have tried both but still having the same issue...?

**Comment by jalendport** [comment]
@terryupton you can always install them by dropping the xml files into a `templates` folder in your PhpStorm [config directory](https://www.jetbrains.com/help/phpstorm/tuning-the-ide.html#config-directory). That's how I installed them (back before PhpStorm 2018.3 added support for adding them via Preferences like everyone's mentioning above).

![image](https://user-images.githubusercontent.com/6537823/53645129-364d0b80-3c06-11e9-9309-e8e1ffe2c04f.png)

**Comment by terryupton** [comment]
Thanks @jalendport - this is exactly what I have just done. Seems to work for now.

**Comment by BenParizek** [comment]
I'm closing this out as there is a suggested workaround above and any deeper issue is likely a PhpStorm issue as it is also working in some cases just fine. If anybody runs into any new scenarios worth sharing, feel free to create a new issue or share the info and we can reopen.
