### ISSUE TITLE
Starting from version 2022.3, the Settings Repository plugin is not bundled with PhpStorm

### ISSUE THREAD

**Issue by bartdigitalpulse** [BarrelStrength/PhpStorm-Live-Templates-Craft-CMS#4]
FYI: Since version 2022.3 you have to manually install the Settings Repository plugin

https://www.jetbrains.com/help/phpstorm/settings-tools-settings-repository.html

**Comment by BenParizek** [comment]
Thanks, updated the instructions. And, I find CoPilot's usefulness encroaching very quickly on these Live Templates!
